---
# create UCS orgs

- hosts: ucs.vm.jm
  connection: local
  gather_facts: no
  vars:
    orgs:
      - name: linux
        description: Top Linux org
        org_path: root
      - name: linux-core
        description: Linux core sub org
        org_path: root/linux
      - name: windows
        description: Top Windows org
        org_path: root
      - name: windows-dmz
        description: Windows dmz sub org
        org_path: root/windows

  tasks:
  - name: Add organizations
    ucs_org:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

      org_name: "{{ item.name }}"
      description: "{{ item.description }}"
      parent_org_path: "{{ item.org_path }}"
      state: present
      delegate_to: localhost
    loop: "{{ orgs }}"